onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/rx_gasket/clk_to_get
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/rx_gasket/PCLK
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/rx_gasket/Rst_n
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/rx_gasket/Rx_Datak
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/rx_gasket/width
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/rx_gasket/Data_in
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/rx_gasket/Data_out
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/rx_gasket/data_out
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/rx_gasket/count
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/rx_gasket/flag
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/rx_gasket/temp_reg
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/CLK
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/Rst_n
add wave -noupdate -radix unsigned /top/DUT/PCS_U/PCS_RX_U/decode/Data_in
add wave -noupdate -radix binary /top/DUT/PCS_U/PCS_RX_U/decode/Data_in
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/Data_out
add wave -noupdate -radix unsigned /top/DUT/PCS_U/PCS_RX_U/decode/DecodeError
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/DisparityError
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/RxDataK
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/temp
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/encoded_data_N
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/encoded_data_P
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/DecodeError_N
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/DecodeError_P
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/RxDataK_N
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/RxDataK_P
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/flag
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/flag_n
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/flag_p
add wave -noupdate /top/DUT/Ref_CLK
add wave -noupdate /top/DUT/Reset_n
add wave -noupdate /top/DUT/DataBusWidth
add wave -noupdate /top/DUT/MAC_TX_Data
add wave -noupdate /top/DUT/MAC_TX_DataK
add wave -noupdate /top/DUT/MAC_Data_En
add wave -noupdate /top/DUT/RxPolarity
add wave -noupdate /top/DUT/TX_Out_P
add wave -noupdate /top/DUT/TX_Out_N
add wave -noupdate /top/DUT/RX_Data
add wave -noupdate /top/DUT/RX_DataK
add wave -noupdate /top/DUT/RX_Status
add wave -noupdate /top/DUT/RX_Valid
add wave -noupdate /top/DUT/PCLK
add wave -noupdate /top/DUT/recovered_clk_5G
add wave -noupdate /top/DUT/Data_In_PMA
add wave -noupdate /top/DUT/Data_Out_PMA
add wave -noupdate /top/DUT/Bit_Rate_Clk
add wave -noupdate /top/DUT/Bit_Rate_CLK_10
add wave -noupdate /top/DUT/TX_P
add wave -noupdate /top/DUT/TX_N
add wave -noupdate /top/DUT/Bit_Rate_Clk_offset
add wave -noupdate /top/DUT/PMA_U/PM_RX_U/serialToparallel/Recovered_Bit_Clk
add wave -noupdate /top/DUT/PMA_U/PM_RX_U/serialToparallel/Ser_in
add wave -noupdate /top/DUT/PMA_U/PM_RX_U/serialToparallel/Rst_n
add wave -noupdate /top/DUT/PMA_U/PM_RX_U/serialToparallel/RxPolarity
add wave -noupdate /top/DUT/PMA_U/PM_RX_U/serialToparallel/Data_Collected
add wave -noupdate /top/DUT/PMA_U/PM_RX_U/serialToparallel/serial
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/write_clk
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/read_clk
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/data_in
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/rst_n
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/skp_added
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/Skp_Removed
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/overflow
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/underflow
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/data_out
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/gray_write_pointer
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/gray_read_pointer
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/write_address
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/read_address
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/sync_gray_read_out
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/sync_gray_write_out
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/delete_req
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/buffer/add_req
add wave -noupdate /top/DUT/PCS_U/PCS_TX_U/Encoding_U/line_coding_8_10_U/enable
add wave -noupdate /top/DUT/PCS_U/PCS_TX_U/Encoding_U/line_coding_8_10_U/TXDataK
add wave -noupdate /top/DUT/PCS_U/PCS_TX_U/Encoding_U/line_coding_8_10_U/data
add wave -noupdate /top/DUT/PCS_U/PCS_TX_U/Encoding_U/line_coding_8_10_U/encoded_data_pos
add wave -noupdate /top/DUT/PCS_U/PCS_TX_U/Encoding_U/line_coding_8_10_U/encoded_data_neg
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/CLK
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/Rst_n
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/Data_in
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/Data_out
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/DecodeError
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/DisparityError
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/RxDataK
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/temp
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/encoded_data_N
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/encoded_data_P
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/DecodeError_N
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/DecodeError_P
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/RxDataK_N
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/RxDataK_P
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/flag
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/flag_n
add wave -noupdate /top/DUT/PCS_U/PCS_RX_U/decode/flag_p
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2031 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 441
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {2006 fs} {2047 fs}
